ui: mocha-bdd
scripts:
  - "/config.js"
  - "/domain.js"
server: ./tests/support/sockjs_server.js
coverage: false
concurrency: 5
tunnel:
  type: ngrok
  proto: tcp
capabilities:
  record-video: false
  record-screenshots: false
  avoid-proxy: true
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  # - name: iphone
  #   version: latest
  - name: android
    version: latest
